const HOMEPAGE_IMAGES = {
  transportMenu: require("@/assets/homepage/transport.png"),
  foodMenu: require("@/assets/homepage/food.png"),
  martMenu: require("@/assets/homepage/mart.png"),
  deliveryMenu: require("@/assets/homepage/delivery.png"),
  allMenu: require("@/assets/homepage/all.png"),
  topUp: require("@/assets/homepage/topup.png"),
  superbank: require("@/assets/homepage/superbank.png"),
  crown: require("@/assets/homepage/crown.png"),
  ads1: require("@/assets/homepage/ads-1.png"),
  ads2: require("@/assets/homepage/ads-2.png"),
  ads3: require("@/assets/homepage/ads-3.png"),
  ads4: require("@/assets/homepage/ads-4.png"),
  ads5: require("@/assets/homepage/ads-5.png"),
  food1: require("@/assets/homepage/food-1.png"),
  food2: require("@/assets/homepage/food-2.png"),
  food3: require("@/assets/homepage/food-3.png"),
  food4: require("@/assets/homepage/food-4.png"),
  food5: require("@/assets/homepage/food-5.png"),
  food6: require("@/assets/homepage/food-6.png"),
  food7: require("@/assets/homepage/food-7.png"),
  food8: require("@/assets/homepage/food-8.png"),
  food9: require("@/assets/homepage/food-9.png"),
  food10: require("@/assets/homepage/food-10.png"),
  challenge1: require("@/assets/homepage/challenge-1.png"),
  challenge2: require("@/assets/homepage/challenge-2.png"),
  promo1: require("@/assets/homepage/promo-1.png"),
  promo2: require("@/assets/homepage/promo-2.png"),
  promo3: require("@/assets/homepage/promo-3.png"),
  grabExpress1: require("@/assets/homepage/grab-express-1.png"),
  grabExpress2: require("@/assets/homepage/grab-express-2.png"),
  questionMark: require("@/assets/homepage/question-mark.png"),
  paper: require("@/assets/homepage/paper.png"),
};

export default HOMEPAGE_IMAGES;
